"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { StoreHeader } from "@/components/StoreHeader";
import { useCart } from "@/lib/cart";
import { api, money } from "@/lib/api";
import type { Customer, Order } from "@/lib/types";

export default function CheckoutPage() { const cart=useCart(); const router=useRouter(); const [customers,setCustomers]=useState<Customer[]>([]); const [customerId,setCustomerId]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{ api<Customer[]>("/api/v1/customers").then((rows)=>{setCustomers(rows);const saved=localStorage.getItem("blubird-customer");setCustomerId(saved && rows.some((c)=>String(c.id)===saved) ? saved : String(rows[0]?.id||""));}).catch((err:Error)=>setError(err.message)); },[]);
  const shipping=cart.subtotal>=7500?0:795; async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!customerId||!cart.items.length)return;setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const order=await api<Order>("/api/v1/orders",{method:"POST",body:JSON.stringify({customer_id:Number(customerId),items:cart.items.map(({product,quantity})=>({product_id:product.id,quantity})),notes:`Ship to: ${form.get("name")}, ${form.get("address")}, ${form.get("city")} · Phone: ${form.get("phone")} · Payment: ${form.get("payment")}`})});cart.clear();localStorage.setItem("blubird-customer",customerId);router.push(`/order-confirmation/${order.id}`);}catch(err){setError((err as Error).message);setBusy(false);}}
  if(!cart.items.length)return <><StoreHeader/><div className="empty-state"><h1>No items to checkout</h1><Link href="/cart">Return to cart</Link></div></>;
  return <><StoreHeader/><main className="page-wrap narrow"><nav className="checkout-steps"><span>✓ <em>Cart</em></span><i/><b>2 <span>Checkout</span></b><i/><span>3 <em>Confirmation</em></span></nav><div className="page-heading"><div><p className="section-kicker">Secure checkout</p><h1>Complete your order</h1></div></div><form onSubmit={submit} className="commerce-layout checkout-form"><section><div className="form-card"><h2><span>1</span> Contact information</h2><label>Shopping as<select value={customerId} onChange={(e)=>setCustomerId(e.target.value)} required>{customers.map((c)=><option value={c.id} key={c.id}>{c.name} · {c.email}</option>)}</select></label><div className="form-grid"><label>Full name<input name="name" required placeholder="Your full name"/></label><label>Phone number<input name="phone" required placeholder="01XXXXXXXXX"/></label></div></div><div className="form-card"><h2><span>2</span> Delivery address</h2><label>Street address<input name="address" required placeholder="House, road, area"/></label><div className="form-grid"><label>City<input name="city" required defaultValue="Dhaka"/></label><label>Postal code<input name="postal" placeholder="1207"/></label></div></div><div className="form-card"><h2><span>3</span> Payment</h2><label className="payment-option"><input type="radio" name="payment" value="cash" defaultChecked/><span><b>Cash on delivery</b><small>Pay when your order arrives</small></span></label><label className="payment-option"><input type="radio" name="payment" value="card"/><span><b>Card on delivery</b><small>Visa, Mastercard, or mobile banking</small></span></label></div></section><aside className="order-summary"><h2>Your order</h2>{cart.items.map(({product,quantity})=><div className="mini-item" key={product.id}><img src={product.image_url} alt=""/><span>{product.name}<small>Qty {quantity}</small></span><b>{money(product.price_cents*quantity)}</b></div>)}<hr/><p><span>Subtotal</span><b>{money(cart.subtotal)}</b></p><p><span>Delivery</span><b>{shipping?money(shipping):"Free"}</b></p><p className="summary-total"><span>Total</span><b>{money(cart.subtotal+shipping)}</b></p><button className="btn-primary" disabled={busy}>{busy?"Placing order…":"Place order →"}</button>{error?<p className="form-error">{error}</p>:null}<small>By placing your order, you agree to our terms and returns policy.</small></aside></form></main></>;
}
